# vim: ft=gitconfig

[include]
  path = ~/.gitconfig.local

[init]
  defaultBranch = main

[core]
  ignorecase = false
  pager = less -FX
  fsmonitor = true
  untrackedCache = true
  whitespace = trailing-space,space-before-tab

[help]
  autocorrect = 1

[commit]
  verbose = true

[diff]
  algorithm = histogram
  colorMoved = default
  renames = true
  mnemonicPrefix = true
  ignoreSpaceChange = true

[merge]
  conflictstyle = zdiff3

[rebase]
  autoStash = true
  abbreviateCommands = true
  updateRefs = true
  missingCommitsCheck = warn

[pull]
  rebase = true

[push]
  autoSetupRemote = true

[fetch]
  prune = true
  pruneTags = true

[checkout]
  defaultRemote = origin

[branch]
  sort = -committerdate
  autosetuprebase = always

[tag]
  sort = version:refname

[status]
  short = true
  branch = true

[log]
  decorate = short

[color]
  ui = true

[column]
  ui = auto

[rerere]
  enabled = true

[pack]
  useSparse = true

[protocol]
  version = 2

[feature]
  manyFiles = true
