# Schema configuration
"$schema" = "https://starship.rs/config-schema.json"

# Color Scheme: https://tailwindcss.com/docs/customizing-colors
# Slate 500: #64748b
# Slate 700: #334155
# Blue 300: #93c5fd
# Red 300: #fda4af
# Amber 300: #fcd34d

format = """
[](fg:#93c5fd)\
$username\
$hostname\
[](fg:prev_bg bg:#334155)\
$directory\
$git_branch\
$git_status\
[](fg:prev_bg)
[%](fg:#64748b) """

right_format = """
[](fg:#fcd34d)\
$time\
[](fg:#fcd34d)\
"""

scan_timeout = 30
command_timeout = 100

[username]
style_user = "fg:#334155 bg:#93c5fd"
style_root = "fg:#334155 bg:#93c5fd"
format = '[$user]($style)'
show_always = true

[hostname]
style = "fg:prev_fg bg:prev_bg"
format = "[@]($style)[$hostname ]($style bold)"
ssh_only = false

[directory]
style = "bg:prev_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
style = "bg:prev_bg"
format = '[](fg:prev_fg bg:prev_bg)[ $symbol $branch ]($style)'
symbol = ""

[git_status]
style = "bg:prev_bg"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
style = "fg:#334155 bg:#fcd34d"
format = "[$time]($style)"
