"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$directory$character"

[directory]
truncate_to_repo = true
style = ""

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"
