# For more information, please visit https://starship.rs/guide/

scan_timeout = 20
command_timeout = 100
add_newline = true

format = """
$directory$git_branch$git_commit$git_state$git_metrics$git_status
[$username@$hostname](underline) %% 
"""

[directory]
style = "bold cyan"
read_only_style = "bold red"
truncation_symbol = ".../"

[username]
format = "$user"
style_user = "bold green"
style_root = "bold red"
show_always = true

[hostname]
format = "$hostname"
ssh_only = false
