#!/usr/bin/zsh

silent() {
  $@ >/dev/null 2>/dev/null
  return $?
}

typeset -U PATH
typeset -U FPATH

ZSH_ROOT="$(dirname $(readlink ~/.zshrc))"

export HISTFILE=~/.zsh_history
export HISTSIZE=262144
export SAVEHIST=262144

export FPATH="${FPATH}:${ZSH_ROOT}/functions"

[ ${+EDITOR} -ne 1 ] && silent which nvim && export EDITOR="nvim"
[ ${+EDITOR} -ne 1 ] && silent which vim && export EDITOR="vim"
[ ${+EDITOR} -ne 1 ] && silent which vi && export EDITOR="vi"

source "${XDG_DATA_HOME}/zinit/zinit.zsh"

zinit light mafredri/zsh-async
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-syntax-highlighting


stty -ixon -ixoff

autoload -Uz cdtemp
autoload -Uz compinit
autoload -Uz promptinit

promptinit
prompt protheme

compinit
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 2 numeric
zstyle ':completion:*:functions' ignored-patterns '_*'

setopt correct

# aliases

alias ls="ls -G"
alias reload="exec ${SHELL}"
alias -g foreach="xargs -n 1 -I {}"

# bindkeys

bindkey -e
bindkey -r "^b"; bindkey "^b" backward-word
bindkey -r "^f"; bindkey "^f" forward-word
bindkey -r "^[[A"; bindkey "^[[A" up-line-or-search
bindkey -r "^[[B"; bindkey "^[[B" down-line-or-search

# binary packages

zinit ice as:"program" from:"gh-r" ver:"0.27.2" pick:"fzf"
zinit light junegunn/fzf

zinit ice as:"program" from:"gh-r" ver:"jq-1.6" cp:"jq-osx-amd64 -> jq" pick:"jq"
zinit light stedolan/jq

[ -f "~/.zshrc.local" ] && source ~/.zshrc.local

which zprof >/dev/null 2>/dev/null && zprof
